export { AuthProvider } from './hooks/AuthProvider';
export { AuthContext } from './hooks/authContext';
export { useAuth } from './hooks/useAuth';
export { default as LoginPage } from './ui/LoginPage';
export { default as RegisterPage } from './ui/RegisterPage';
export { ProtectedRoute } from './ui/ProtectedRoute';
export { PublicOnlyRoute } from './ui/PublicOnlyRoute';
export { AdminRoute } from './ui/AdminRoute';
export { TeacherRoute } from './ui/TeacherRoute';
export { isUserAdmin } from './domain/adminAuthorization';
export { isUserTeacher } from './domain/teacherAuthorization';
export { createUserProfile } from './domain/userProfile';
export { userProfileRepository } from './data/userProfileRepository';
